# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.backupPathLabel = QtWidgets.QLabel(self.centralwidget)
        self.backupPathLabel.setObjectName("backupPathLabel")
        self.horizontalLayout_2.addWidget(self.backupPathLabel)
        self.editBackupPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.editBackupPathButton.setObjectName("editBackupPathButton")
        self.horizontalLayout_2.addWidget(self.editBackupPathButton)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backupSelectedButton = QtWidgets.QPushButton(self.centralwidget)
        self.backupSelectedButton.setObjectName("backupSelectedButton")
        self.horizontalLayout.addWidget(self.backupSelectedButton)
        self.loadSelectedButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadSelectedButton.setObjectName("loadSelectedButton")
        self.horizontalLayout.addWidget(self.loadSelectedButton)
        self.backupAll = QtWidgets.QPushButton(self.centralwidget)
        self.backupAll.setObjectName("backupAll")
        self.horizontalLayout.addWidget(self.backupAll)
        self.addNewButton = QtWidgets.QPushButton(self.centralwidget)
        self.addNewButton.setObjectName("addNewButton")
        self.horizontalLayout.addWidget(self.addNewButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Backup Manager"))
        self.label.setText(_translate("MainWindow", "Backup Path:"))
        self.backupPathLabel.setText(_translate("MainWindow", "backup_path here"))
        self.editBackupPathButton.setText(_translate("MainWindow", "Edit"))
        self.backupSelectedButton.setText(_translate("MainWindow", "Backup Marked"))
        self.loadSelectedButton.setText(_translate("MainWindow", "Load Marked"))
        self.backupAll.setText(_translate("MainWindow", "Backup All"))
        self.addNewButton.setText(_translate("MainWindow", "Add a Directory"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
